import type { Opportunity } from "./schemas.js";

export const SAMPLES: Opportunity[] = [
  {
    id: "meridian-logistics",
    company: "Meridian Logistics Platform Expansion",
    stage: "Negotiation",
    arr: 420_000,
    expectedCloseDate: "2026-08-15",
    activityLevel: 9,
    daysSinceLastTouch: 2,
    budgetConfirmed: true,
    economicBuyerIdentified: true,
    execSponsorEngaged: true,
    pilotStatus: "successful",
    securityReview: "complete",
    discoveryComplete: true,
    mutualActionPlan: true,
    competitorInDeal: false,
    notes:
      "VP Supply Chain signed off on ROI model last week. Legal redlines are minor. Procurement expects PO by mid-August after final security attestation packet.",
  },
  {
    id: "frontier-automotive",
    company: "Frontier Automotive New Business",
    stage: "Evaluation",
    arr: 285_000,
    expectedCloseDate: "2026-09-30",
    activityLevel: 4,
    daysSinceLastTouch: 18,
    budgetConfirmed: false,
    economicBuyerIdentified: true,
    execSponsorEngaged: false,
    pilotStatus: "in progress",
    securityReview: "in progress",
    discoveryComplete: true,
    mutualActionPlan: false,
    competitorInDeal: false,
    notes:
      "Champion loves the platform narrative and wants a dashboard for the board. Security questionnaire is half done. No confirmed budget line yet and the last exec sync was rescheduled twice.",
  },
  {
    id: "cobalt-health",
    company: "Cobalt Health Discovery",
    stage: "Discovery",
    arr: 95_000,
    expectedCloseDate: "2026-12-01",
    activityLevel: 3,
    daysSinceLastTouch: 9,
    budgetConfirmed: false,
    economicBuyerIdentified: false,
    execSponsorEngaged: false,
    pilotStatus: "not started",
    securityReview: "not started",
    discoveryComplete: false,
    mutualActionPlan: false,
    competitorInDeal: false,
    notes:
      "Two discovery calls completed. Use case is vague: 'better visibility into patient intake.' No timeline from their side yet.",
  },
  {
    id: "atlas-media",
    company: "Atlas Media Enterprise Deal",
    stage: "Proposal",
    arr: 310_000,
    expectedCloseDate: "2026-07-31",
    activityLevel: 6,
    daysSinceLastTouch: 5,
    budgetConfirmed: true,
    economicBuyerIdentified: true,
    execSponsorEngaged: false,
    pilotStatus: "successful",
    securityReview: "complete",
    discoveryComplete: true,
    mutualActionPlan: false,
    competitorInDeal: true,
    notes:
      "Strong product fit from pilot. Competitor (Streamline) offered 15% discount. RevOps lead is engaged but no C-level sponsor on our side of the table yet.",
  },
  {
    id: "nimbus-robotics",
    company: "Nimbus Robotics Renewal Rescue",
    stage: "Closing",
    arr: 175_000,
    expectedCloseDate: "2026-07-20",
    activityLevel: 1,
    daysSinceLastTouch: 42,
    budgetConfirmed: false,
    economicBuyerIdentified: false,
    execSponsorEngaged: false,
    pilotStatus: "failed",
    securityReview: "not started",
    discoveryComplete: true,
    mutualActionPlan: false,
    competitorInDeal: true,
    notes:
      "Pilot missed uptime SLA in March. Customer went quiet after escalation. Renewal date is imminent and they are evaluating a build-vs-buy path with a systems integrator.",
  },
];
